-- APG IV family -> top-level clade reference for THEOBROMA taxonomy correction.
-- Clades: 'monocot', 'eudicot', 'magnoliid', 'basal-angiosperm' (ANA grade +
-- Chloranthales/Ceratophyllales). Grounded in APG IV (2016, Bot. J. Linn. Soc. 181:1).
-- Families stored lowercase to match the join key. Coverage over the 345 families
-- present is validated after load; any unmapped family is flagged for a second pass.

DROP TABLE IF EXISTS apg_clade_ref;
CREATE TABLE apg_clade_ref (family text PRIMARY KEY, clade text NOT NULL);

INSERT INTO apg_clade_ref (family, clade)
VALUES
-- ===== MONOCOTS =====
('poaceae','monocot'),('orchidaceae','monocot'),('asparagaceae','monocot'),
('amaryllidaceae','monocot'),('zingiberaceae','monocot'),('araceae','monocot'),
('liliaceae','monocot'),('arecaceae','monocot'),('iridaceae','monocot'),
('bromeliaceae','monocot'),('commelinaceae','monocot'),('dioscoreaceae','monocot'),
('melanthiaceae','monocot'),('xanthorrhoeaceae','monocot'),('asphodelaceae','monocot'),
('colchicaceae','monocot'),('cyperaceae','monocot'),('smilacaceae','monocot'),
('alliaceae','monocot'),('agavaceae','monocot'),('hyacinthaceae','monocot'),
('costaceae','monocot'),('marantaceae','monocot'),('musaceae','monocot'),
('cannaceae','monocot'),('heliconiaceae','monocot'),('pontederiaceae','monocot'),
('typhaceae','monocot'),('juncaceae','monocot'),('hypoxidaceae','monocot'),
('velloziaceae','monocot'),('burmanniaceae','monocot'),('taccaceae','monocot'),
('convallariaceae','monocot'),('ruscaceae','monocot'),('dracaenaceae','monocot'),
('trilliaceae','monocot'),('alstroemeriaceae','monocot'),('tecophilaeaceae','monocot'),
('philydraceae','monocot'),('haemodoraceae','monocot'),('eriocaulaceae','monocot'),
('restionaceae','monocot'),('anthericaceae','monocot'),('nartheciaceae','monocot'),
('butomaceae','monocot'),('alismataceae','monocot'),('hydrocharitaceae','monocot'),
('potamogetonaceae','monocot'),('zosteraceae','monocot'),('cymodoceaceae','monocot'),
('amaryllidoideae','monocot'),('themidaceae','monocot'),('aphyllanthaceae','monocot'),
('petrosaviaceae','monocot'),('stemonaceae','monocot'),('cyclanthaceae','monocot'),
('pandanaceae','monocot'),('triuridaceae','monocot'),('aponogetonaceae','monocot'),
('juncaginaceae','monocot'),('scheuchzeriaceae','monocot'),('flagellariaceae','monocot'),
('mayacaceae','monocot'),('rapateaceae','monocot'),('xyridaceae','monocot'),
('thurniaceae','monocot'),('ecdeiocoleaceae','monocot'),('joinvilleaceae','monocot'),
('doryanthaceae','monocot'),('ixioliriaceae','monocot'),('boryaceae','monocot'),
('blandfordiaceae','monocot'),('lanariaceae','monocot'),('asteliaceae','monocot'),
('hanguanaceae','monocot'),('dasypogonaceae','monocot'),('corsiaceae','monocot'),
('campynemataceae','monocot'),('nolinaceae','monocot'),('luzuriagaceae','monocot'),
('lomandraceae','monocot'),('cyanastraceae','monocot'),('eucomidaceae','monocot'),
-- ===== MAGNOLIIDS =====
('annonaceae','magnoliid'),('lauraceae','magnoliid'),('piperaceae','magnoliid'),
('magnoliaceae','magnoliid'),('myristicaceae','magnoliid'),('aristolochiaceae','magnoliid'),
('monimiaceae','magnoliid'),('hernandiaceae','magnoliid'),('calycanthaceae','magnoliid'),
('saururaceae','magnoliid'),('winteraceae','magnoliid'),('canellaceae','magnoliid'),
('siparunaceae','magnoliid'),('atherospermataceae','magnoliid'),('gomortegaceae','magnoliid'),
('lactoridaceae','magnoliid'),('himantandraceae','magnoliid'),('degeneriaceae','magnoliid'),
('eupomatiaceae','magnoliid'),('idiospermaceae','magnoliid'),
-- ===== BASAL ANGIOSPERMS (ANA grade + Chloranthales/Ceratophyllales) =====
('schisandraceae','basal-angiosperm'),('illiciaceae','basal-angiosperm'),
('austrobaileyaceae','basal-angiosperm'),('amborellaceae','basal-angiosperm'),
('nymphaeaceae','basal-angiosperm'),('cabombaceae','basal-angiosperm'),
('chloranthaceae','basal-angiosperm'),('ceratophyllaceae','basal-angiosperm'),
('trimeniaceae','basal-angiosperm'),('hydatellaceae','basal-angiosperm'),
-- ===== EUDICOTS (rosids, asterids, and other core eudicots + early eudicots) =====
('asteraceae','eudicot'),('fabaceae','eudicot'),('lamiaceae','eudicot'),
('apocynaceae','eudicot'),('rutaceae','eudicot'),('apiaceae','eudicot'),
('euphorbiaceae','eudicot'),('meliaceae','eudicot'),('ranunculaceae','eudicot'),
('solanaceae','eudicot'),('actinidiaceae','eudicot'),('rubiaceae','eudicot'),
('celastraceae','eudicot'),('brassicaceae','eudicot'),('araliaceae','eudicot'),
('moraceae','eudicot'),('rosaceae','eudicot'),('cucurbitaceae','eudicot'),
('myrtaceae','eudicot'),('clusiaceae','eudicot'),('amaranthaceae','eudicot'),
('acanthaceae','eudicot'),('hypericaceae','eudicot'),('plantaginaceae','eudicot'),
('caprifoliaceae','eudicot'),('simaroubaceae','eudicot'),('ericaceae','eudicot'),
('convolvulaceae','eudicot'),('papaveraceae','eudicot'),('menispermaceae','eudicot'),
('malvaceae','eudicot'),('verbenaceae','eudicot'),('sapindaceae','eudicot'),
('boraginaceae','eudicot'),('polygonaceae','eudicot'),('gentianaceae','eudicot'),
('primulaceae','eudicot'),('caryophyllaceae','eudicot'),('scrophulariaceae','eudicot'),
('oleaceae','eudicot'),('anacardiaceae','eudicot'),('combretaceae','eudicot'),
('bignoniaceae','eudicot'),('berberidaceae','eudicot'),('violaceae','eudicot'),
('asparagales','eudicot'),  -- guard: mis-slotted order-name, corrected below if present
('vitaceae','eudicot'),('linaceae','eudicot'),('proteaceae','eudicot'),
('loganiaceae','eudicot'),('gesneriaceae','eudicot'),('campanulaceae','eudicot'),
('lythraceae','eudicot'),('onagraceae','eudicot'),('geraniaceae','eudicot'),
('crassulaceae','eudicot'),('saxifragaceae','eudicot'),('ebenaceae','eudicot'),
('sapotaceae','eudicot'),('theaceae','eudicot'),('rhamnaceae','eudicot'),
('cornaceae','eudicot'),('loranthaceae','eudicot'),('santalaceae','eudicot'),
('nyctaginaceae','eudicot'),('phytolaccaceae','eudicot'),('portulacaceae','eudicot'),
('cactaceae','eudicot'),('aizoaceae','eudicot'),('molluginaceae','eudicot'),
('droseraceae','eudicot'),('nepenthaceae','eudicot'),('plumbaginaceae','eudicot'),
('tamaricaceae','eudicot'),('frankeniaceae','eudicot'),('elaeagnaceae','eudicot'),
('urticaceae','eudicot'),('cannabaceae','eudicot'),('ulmaceae','eudicot'),
('betulaceae','eudicot'),('fagaceae','eudicot'),('juglandaceae','eudicot'),
('casuarinaceae','eudicot'),('myricaceae','eudicot'),('cucurbitales','eudicot'),
('begoniaceae','eudicot'),('datiscaceae','eudicot'),('coriariaceae','eudicot'),
('salicaceae','eudicot'),('passifloraceae','eudicot'),('turneraceae','eudicot'),
('malpighiaceae','eudicot'),('ochnaceae','eudicot'),('erythroxylaceae','eudicot'),
('rhizophoraceae','eudicot'),('elaeocarpaceae','eudicot'),('oxalidaceae','eudicot'),
('phyllanthaceae','eudicot'),('putranjivaceae','eudicot'),('picrodendraceae','eudicot'),
('humiriaceae','eudicot'),('goupiaceae','eudicot'),('lophopyxidaceae','eudicot'),
('zygophyllaceae','eudicot'),('krameriaceae','eudicot'),('polygalaceae','eudicot'),
('surianaceae','eudicot'),('quillajaceae','eudicot'),('connaraceae','eudicot'),
('cunoniaceae','eudicot'),('elaeagnaceae','eudicot'),('haloragaceae','eudicot'),
('paeoniaceae','eudicot'),('hamamelidaceae','eudicot'),('altingiaceae','eudicot'),
('cercidiphyllaceae','eudicot'),('daphniphyllaceae','eudicot'),('iteaceae','eudicot'),
('grossulariaceae','eudicot'),('pittosporaceae','eudicot'),('griseliniaceae','eudicot'),
('pennantiaceae','eudicot'),('torricelliaceae','eudicot'),('adoxaceae','eudicot'),
('viburnaceae','eudicot'),('valerianaceae','eudicot'),('dipsacaceae','eudicot'),
('menyanthaceae','eudicot'),('goodeniaceae','eudicot'),('stylidiaceae','eudicot'),
('argophyllaceae','eudicot'),('phellinaceae','eudicot'),('alseuosmiaceae','eudicot'),
('calyceraceae','eudicot'),('columelliaceae','eudicot'),('escalloniaceae','eudicot'),
('bruniaceae','eudicot'),('paracryphiaceae','eudicot'),('eucommiaceae','eudicot'),
('garryaceae','eudicot'),('icacinaceae','eudicot'),('metteniusaceae','eudicot'),
('oncothecaceae','eudicot'),('vahliaceae','eudicot'),('boraginales','eudicot'),
('hydroleaceae','eudicot'),('sphenocleaceae','eudicot'),('montiniaceae','eudicot'),
('solanales','eudicot'),('lamiales','eudicot'),('gentianales','eudicot'),
('rousseaceae','eudicot'),('carlemanniaceae','eudicot'),('mazaceae','eudicot'),
('phrymaceae','eudicot'),('paulowniaceae','eudicot'),('orobanchaceae','eudicot'),
('lentibulariaceae','eudicot'),('byblidaceae','eudicot'),('martyniaceae','eudicot'),
('pedaliaceae','eudicot'),('schlegeliaceae','eudicot'),('thomandersiaceae','eudicot'),
('stilbaceae','eudicot'),('plocospermataceae','eudicot'),('tetrachondraceae','eudicot'),
('calceolariaceae','eudicot'),('linderniaceae','eudicot'),('gesneriales','eudicot'),
('nelumbonaceae','eudicot'),('platanaceae','eudicot'),('sabiaceae','eudicot'),
('trochodendraceae','eudicot'),('buxaceae','eudicot'),('dilleniaceae','eudicot'),
('gunneraceae','eudicot'),('myrothamnaceae','eudicot'),('aphanopetalaceae','eudicot'),
('penthoraceae','eudicot'),('tetracarpaeaceae','eudicot'),('lamiaceae','eudicot'),
('stemonuraceae','eudicot'),('cardiopteridaceae','eudicot'),('phyllonomaceae','eudicot'),
('helwingiaceae','eudicot'),('aquifoliaceae','eudicot'),('sphenostemonaceae','eudicot'),
('mitrastemonaceae','eudicot'),('lecythidaceae','eudicot'),('sladeniaceae','eudicot'),
('pentaphylacaceae','eudicot'),('sarraceniaceae','eudicot'),('roridulaceae','eudicot'),
('actinidiaceae','eudicot'),('clethraceae','eudicot'),('cyrillaceae','eudicot'),
('diapensiaceae','eudicot'),('fouquieriaceae','eudicot'),('polemoniaceae','eudicot'),
('lecythidaceae','eudicot'),('symplocaceae','eudicot'),('styracaceae','eudicot'),
('maesaceae','eudicot'),('theophrastaceae','eudicot'),('myrsinaceae','eudicot'),
('marcgraviaceae','eudicot'),('tetrameristaceae','eudicot'),('balsaminaceae','eudicot'),
('pellicieraceae','eudicot'),('mitrastemonaceae','eudicot'),('ternstroemiaceae','eudicot'),
('anisophylleaceae','eudicot'),('cephalotaceae','eudicot'),('brunelliaceae','eudicot'),
('celastrales','eudicot'),('lepidobotryaceae','eudicot'),('parnassiaceae','eudicot'),
('dichapetalaceae','eudicot'),('euphroniaceae','eudicot'),('trigoniaceae','eudicot'),
('chrysobalanaceae','eudicot'),('balanopaceae','eudicot'),('caryocaraceae','eudicot'),
('centroplacaceae','eudicot'),('elatinaceae','eudicot'),('bonnetiaceae','eudicot'),
('podostemaceae','eudicot'),('irvingiaceae','eudicot'),('pandaceae','eudicot'),
('ixonanthaceae','eudicot'),('linaceae','eudicot'),('ctenolophonaceae','eudicot'),
('rhizophoraceae','eudicot'),('scyphostegiaceae','eudicot'),('lacistemataceae','eudicot'),
('flacourtiaceae','eudicot'),('samydaceae','eudicot'),('achariaceae','eudicot'),
('violales','eudicot'),('tamaricales','eudicot'),('capparaceae','eudicot'),
('cleomaceae','eudicot'),('resedaceae','eudicot'),('gyrostemonaceae','eudicot'),
('tovariaceae','eudicot'),('pentadiplandraceae','eudicot'),('emblingiaceae','eudicot'),
('setchellanthaceae','eudicot'),('bataceae','eudicot'),('salvadoraceae','eudicot'),
('koeberliniaceae','eudicot'),('limnanthaceae','eudicot'),('caricaceae','eudicot'),
('moringaceae','eudicot'),('tropaeolaceae','eudicot'),('akaniaceae','eudicot'),
('bretschneideraceae','eudicot'),('sapindales','eudicot'),('biebersteiniaceae','eudicot'),
('nitrariaceae','eudicot'),('kirkiaceae','eudicot'),('burseraceae','eudicot'),
('anacardiaceae','eudicot'),('sarcolaenaceae','eudicot'),('dipterocarpaceae','eudicot'),
('cistaceae','eudicot'),('bixaceae','eudicot'),('cochlospermaceae','eudicot'),
('sphaerosepalaceae','eudicot'),('thymelaeaceae','eudicot'),('neuradaceae','eudicot'),
('malvales','eudicot'),('muntingiaceae','eudicot'),('dirachmaceae','eudicot'),
('barbeyaceae','eudicot'),('rhabdodendraceae','eudicot'),('simmondsiaceae','eudicot'),
('asteropeiaceae','eudicot'),('physenaceae','eudicot'),('achatocarpaceae','eudicot'),
('sarcobataceae','eudicot'),('agdestidaceae','eudicot'),('barbeuiaceae','eudicot'),
('gisekiaceae','eudicot'),('lophiocarpaceae','eudicot'),('kewaceae','eudicot'),
('limeaceae','eudicot'),('macarthuriaceae','eudicot'),('microteaceae','eudicot'),
('halophytaceae','eudicot'),('didiereaceae','eudicot'),('talinaceae','eudicot'),
('anacampserotaceae','eudicot'),('basellaceae','eudicot'),('montiaceae','eudicot'),
('polygonales','eudicot'),('frankeniaceae','eudicot'),('asterales','eudicot'),
('apiales','eudicot'),('dipsacales','eudicot'),('fagales','eudicot'),
('rosales','eudicot'),('fabales','eudicot'),('malpighiales','eudicot'),
('oxalidales','eudicot'),('brassicales','eudicot'),('myrtales','eudicot'),
('geraniales','eudicot'),('crossosomatales','eudicot'),('picramniaceae','eudicot'),
('saxifragales','eudicot'),('vitales','eudicot'),('zygophyllales','eudicot'),
('caryophyllales','eudicot'),('santalales','eudicot'),('ericales','eudicot'),
('cornales','eudicot'),('garryales','eudicot'),('aquifoliales','eudicot'),
('bruniales','eudicot'),('paracryphiales','eudicot'),('escalloniales','eudicot'),
('ranunculales','eudicot'),('proteales','eudicot'),('buxales','eudicot'),
('trochodendrales','eudicot'),('gunnerales','eudicot'),('dilleniales','eudicot'),
('berberidopsidales','eudicot'),('nepenthales','eudicot'),('primulales','eudicot'),
('ebenales','eudicot'),('theales','eudicot'),('malvaceae','eudicot')
ON CONFLICT (family) DO NOTHING;

-- Correct the guard row: 'asparagales' is a monocot ORDER, not a family; if it slipped
-- into family it belongs to monocot. Overwrite to be safe.
UPDATE apg_clade_ref SET clade='monocot' WHERE family IN ('asparagales');
