-- Phylum to kingdom mapping for lineage-derived tree grouping.
-- The tree groups by the kingdom implied by the resolved lineage,
-- whereas resolved_taxonomy.kingdom holds the majority-voted primary
-- kingdom used for filtering and for the reported kingdom distribution.
-- Archaea and protist phyla map to unresolved, consistent with S2.

DROP TABLE IF EXISTS phylum_kingdom_map;
CREATE TABLE phylum_kingdom_map (phylum text PRIMARY KEY, lineage_kingdom text NOT NULL);
INSERT INTO phylum_kingdom_map (phylum, lineage_kingdom) VALUES
  ('annelida','animal'),
  ('arthropoda','animal'),
  ('bryozoa','animal'),
  ('chordata','animal'),
  ('cnidaria','animal'),
  ('echinodermata','animal'),
  ('hemichordata','animal'),
  ('mollusca','animal'),
  ('nematoda','animal'),
  ('nemertea','animal'),
  ('platyhelminthes','animal'),
  ('porifera','animal'),
  ('actinobacteria','bacteria'),
  ('actinomycetota','bacteria'),
  ('aquificota','bacteria'),
  ('bacillota','bacteria'),
  ('bacteroidota','bacteria'),
  ('campylobacterota','bacteria'),
  ('candidatus tectimicrobiota','bacteria'),
  ('chlorobiota','bacteria'),
  ('chloroflexota','bacteria'),
  ('cyanobacteria','bacteria'),
  ('cyanobacteriota','bacteria'),
  ('deinococcota','bacteria'),
  ('firmicutes','bacteria'),
  ('mycoplasmatota','bacteria'),
  ('myxococcota','bacteria'),
  ('planctomycetota','bacteria'),
  ('proteobacteria','bacteria'),
  ('pseudomonadota','bacteria'),
  ('rhodothermota','bacteria'),
  ('spirochaetota','bacteria'),
  ('thermotogota','bacteria'),
  ('verrucomicrobiota','bacteria'),
  ('ascomycota','fungi'),
  ('basidiobolomycota','fungi'),
  ('basidiomycota','fungi'),
  ('blastocladiomycota','fungi'),
  ('entomophthoromycota','fungi'),
  ('glomeromycota','fungi'),
  ('mortierellomycota','fungi'),
  ('mucoromycota','fungi'),
  ('chlorophyta','plant'),
  ('prasinodermophyta','plant'),
  ('rhodophyta','plant'),
  ('streptophyta','plant'),
  ('tracheophyta','plant'),
  ('bacillariophyta','unresolved'),
  ('ciliophora','unresolved'),
  ('discosea','unresolved'),
  ('euglenozoa','unresolved'),
  ('evosea','unresolved'),
  ('haptophyta','unresolved'),
  ('methanobacteriota','unresolved'),
  ('myzozoa','unresolved'),
  ('ochrophyta','unresolved'),
  ('oomycota','unresolved'),
  ('thermoproteota','unresolved')
;
