"""Backfill phylum/class/order for tier-2 plant families in resolved_taxonomy.
Source: APG IV (2016) for angiosperms, PPG I (2016) for ferns, Ruggiero et al.
(2015) for higher-rank plant taxonomy. Bryophytes and gymnosperms covered.
"""
import subprocess

# family -> (taxorder, taxclass, phylum). Class for plants is Magnoliopsida
# for dicots, Liliopsida for monocots, Polypodiopsida for ferns, etc.
# Phylum is Streptophyta (the streptophyte plant lineage) for nearly all
# vascular and bryophyte plants. Chlorophyta for green algae, Anthocerotophyta
# / Marchantiophyta / Bryophyta for non-vascular embryophytes.

PLANT_FAMILIES = {
    # ===== EUDICOTS (Magnoliopsida) — APG IV =====
    # Order Acorales
    'Acoraceae': ('Acorales', 'Liliopsida', 'Streptophyta'),
    # Order Alismatales
    'Alismataceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Aponogetonaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Araceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Butomaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Cymodoceaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Hydrocharitaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Juncaginaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Posidoniaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Potamogetonaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Ruppiaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Scheuchzeriaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Tofieldiaceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    'Zosteraceae': ('Alismatales', 'Liliopsida', 'Streptophyta'),
    # Order Apiales
    'Apiaceae': ('Apiales', 'Magnoliopsida', 'Streptophyta'),
    'Araliaceae': ('Apiales', 'Magnoliopsida', 'Streptophyta'),
    'Griseliniaceae': ('Apiales', 'Magnoliopsida', 'Streptophyta'),
    'Myodocarpaceae': ('Apiales', 'Magnoliopsida', 'Streptophyta'),
    'Pennantiaceae': ('Apiales', 'Magnoliopsida', 'Streptophyta'),
    'Pittosporaceae': ('Apiales', 'Magnoliopsida', 'Streptophyta'),
    'Torricelliaceae': ('Apiales', 'Magnoliopsida', 'Streptophyta'),
    # Order Aquifoliales
    'Aquifoliaceae': ('Aquifoliales', 'Magnoliopsida', 'Streptophyta'),
    'Cardiopteridaceae': ('Aquifoliales', 'Magnoliopsida', 'Streptophyta'),
    'Helwingiaceae': ('Aquifoliales', 'Magnoliopsida', 'Streptophyta'),
    'Phyllonomaceae': ('Aquifoliales', 'Magnoliopsida', 'Streptophyta'),
    'Stemonuraceae': ('Aquifoliales', 'Magnoliopsida', 'Streptophyta'),
    # Order Arecales
    'Arecaceae': ('Arecales', 'Liliopsida', 'Streptophyta'),
    'Dasypogonaceae': ('Arecales', 'Liliopsida', 'Streptophyta'),
    # Order Asparagales
    'Amaryllidaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Asparagaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Asphodelaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Asteliaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Blandfordiaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Boryaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Doryanthaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Hypoxidaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Iridaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Ixioliriaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Lanariaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Orchidaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Tecophilaeaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Xanthorrhoeaceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    'Xeronemataceae': ('Asparagales', 'Liliopsida', 'Streptophyta'),
    # Order Asterales
    'Alseuosmiaceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Argophyllaceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Asteraceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Calyceraceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Campanulaceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Goodeniaceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Menyanthaceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Pentaphragmataceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Phellinaceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Rousseaceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    'Stylidiaceae': ('Asterales', 'Magnoliopsida', 'Streptophyta'),
    # Order Austrobaileyales
    'Austrobaileyaceae': ('Austrobaileyales', 'Magnoliopsida', 'Streptophyta'),
    'Schisandraceae': ('Austrobaileyales', 'Magnoliopsida', 'Streptophyta'),
    'Trimeniaceae': ('Austrobaileyales', 'Magnoliopsida', 'Streptophyta'),
    # Order Berberidopsidales
    'Aextoxicaceae': ('Berberidopsidales', 'Magnoliopsida', 'Streptophyta'),
    'Berberidopsidaceae': ('Berberidopsidales', 'Magnoliopsida', 'Streptophyta'),
    # Order Boraginales
    'Boraginaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Codonaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Coldeniaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Cordiaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Ehretiaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Heliotropiaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Hoplestigmataceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Hydrophyllaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Lennoaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Namaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    'Wellstediaceae': ('Boraginales', 'Magnoliopsida', 'Streptophyta'),
    # Order Brassicales
    'Akaniaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Bataceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Brassicaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Capparaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Caricaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Cleomaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Emblingiaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Gyrostemonaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Koeberliniaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Limnanthaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Moringaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Pentadiplandraceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Resedaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Salvadoraceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Setchellanthaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Tovariaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    'Tropaeolaceae': ('Brassicales', 'Magnoliopsida', 'Streptophyta'),
    # Order Bruniales
    'Bruniaceae': ('Bruniales', 'Magnoliopsida', 'Streptophyta'),
    'Columelliaceae': ('Bruniales', 'Magnoliopsida', 'Streptophyta'),
    # Order Buxales
    'Buxaceae': ('Buxales', 'Magnoliopsida', 'Streptophyta'),
    'Haptanthaceae': ('Buxales', 'Magnoliopsida', 'Streptophyta'),
    # Order Canellales
    'Canellaceae': ('Canellales', 'Magnoliopsida', 'Streptophyta'),
    'Winteraceae': ('Canellales', 'Magnoliopsida', 'Streptophyta'),
    # Order Caryophyllales
    'Achatocarpaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Aizoaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Amaranthaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Anacampserotaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Ancistrocladaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Asteropeiaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Barbeuiaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Basellaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Cactaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Caryophyllaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Chenopodiaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Didiereaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Dioncophyllaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Droseraceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Drosophyllaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Frankeniaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Gisekiaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Halophytaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Kewaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Limeaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Lophiocarpaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Macarthuriaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Microteaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Molluginaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Montiaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Nepenthaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Nyctaginaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Petiveriaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Phytolaccaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Physenaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Plumbaginaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Polygonaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Portulacaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Rhabdodendraceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Sarcobataceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Simmondsiaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Stegnospermataceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Talinaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Tamaricaceae': ('Caryophyllales', 'Magnoliopsida', 'Streptophyta'),
    # Order Celastrales
    'Celastraceae': ('Celastrales', 'Magnoliopsida', 'Streptophyta'),
    'Lepidobotryaceae': ('Celastrales', 'Magnoliopsida', 'Streptophyta'),
    # Order Ceratophyllales
    'Ceratophyllaceae': ('Ceratophyllales', 'Magnoliopsida', 'Streptophyta'),
    # Order Chloranthales
    'Chloranthaceae': ('Chloranthales', 'Magnoliopsida', 'Streptophyta'),
    # Order Commelinales
    'Commelinaceae': ('Commelinales', 'Liliopsida', 'Streptophyta'),
    'Haemodoraceae': ('Commelinales', 'Liliopsida', 'Streptophyta'),
    'Hanguanaceae': ('Commelinales', 'Liliopsida', 'Streptophyta'),
    'Philydraceae': ('Commelinales', 'Liliopsida', 'Streptophyta'),
    'Pontederiaceae': ('Commelinales', 'Liliopsida', 'Streptophyta'),
    # Order Cornales
    'Cornaceae': ('Cornales', 'Magnoliopsida', 'Streptophyta'),
    'Curtisiaceae': ('Cornales', 'Magnoliopsida', 'Streptophyta'),
    'Grubbiaceae': ('Cornales', 'Magnoliopsida', 'Streptophyta'),
    'Hydrangeaceae': ('Cornales', 'Magnoliopsida', 'Streptophyta'),
    'Hydrostachyaceae': ('Cornales', 'Magnoliopsida', 'Streptophyta'),
    'Loasaceae': ('Cornales', 'Magnoliopsida', 'Streptophyta'),
    'Nyssaceae': ('Cornales', 'Magnoliopsida', 'Streptophyta'),
    # Order Crossosomatales
    'Aphloiaceae': ('Crossosomatales', 'Magnoliopsida', 'Streptophyta'),
    'Crossosomataceae': ('Crossosomatales', 'Magnoliopsida', 'Streptophyta'),
    'Geissolomataceae': ('Crossosomatales', 'Magnoliopsida', 'Streptophyta'),
    'Guamatelaceae': ('Crossosomatales', 'Magnoliopsida', 'Streptophyta'),
    'Stachyuraceae': ('Crossosomatales', 'Magnoliopsida', 'Streptophyta'),
    'Staphyleaceae': ('Crossosomatales', 'Magnoliopsida', 'Streptophyta'),
    'Strasburgeriaceae': ('Crossosomatales', 'Magnoliopsida', 'Streptophyta'),
    # Order Cucurbitales
    'Anisophylleaceae': ('Cucurbitales', 'Magnoliopsida', 'Streptophyta'),
    'Begoniaceae': ('Cucurbitales', 'Magnoliopsida', 'Streptophyta'),
    'Coriariaceae': ('Cucurbitales', 'Magnoliopsida', 'Streptophyta'),
    'Corynocarpaceae': ('Cucurbitales', 'Magnoliopsida', 'Streptophyta'),
    'Cucurbitaceae': ('Cucurbitales', 'Magnoliopsida', 'Streptophyta'),
    'Datiscaceae': ('Cucurbitales', 'Magnoliopsida', 'Streptophyta'),
    'Tetramelaceae': ('Cucurbitales', 'Magnoliopsida', 'Streptophyta'),
    # Order Dilleniales
    'Dilleniaceae': ('Dilleniales', 'Magnoliopsida', 'Streptophyta'),
    # Order Dioscoreales
    'Burmanniaceae': ('Dioscoreales', 'Liliopsida', 'Streptophyta'),
    'Dioscoreaceae': ('Dioscoreales', 'Liliopsida', 'Streptophyta'),
    'Nartheciaceae': ('Dioscoreales', 'Liliopsida', 'Streptophyta'),
    # Order Dipsacales
    'Adoxaceae': ('Dipsacales', 'Magnoliopsida', 'Streptophyta'),
    'Caprifoliaceae': ('Dipsacales', 'Magnoliopsida', 'Streptophyta'),
    'Linnaeaceae': ('Dipsacales', 'Magnoliopsida', 'Streptophyta'),
    'Morinaceae': ('Dipsacales', 'Magnoliopsida', 'Streptophyta'),
    'Valerianaceae': ('Dipsacales', 'Magnoliopsida', 'Streptophyta'),
    'Dipsacaceae': ('Dipsacales', 'Magnoliopsida', 'Streptophyta'),
    # Order Ericales
    'Actinidiaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Balsaminaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Clethraceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Cyrillaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Diapensiaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Ebenaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Ericaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Fouquieriaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Lecythidaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Marcgraviaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Mitrastemonaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Pentaphylacaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Polemoniaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Primulaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Roridulaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Sapotaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Sarraceniaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Sladeniaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Styracaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Symplocaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Tetrameristaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    'Theaceae': ('Ericales', 'Magnoliopsida', 'Streptophyta'),
    # Order Escalloniales
    'Escalloniaceae': ('Escalloniales', 'Magnoliopsida', 'Streptophyta'),
    # Order Fabales
    'Fabaceae': ('Fabales', 'Magnoliopsida', 'Streptophyta'),
    'Leguminosae': ('Fabales', 'Magnoliopsida', 'Streptophyta'),
    'Polygalaceae': ('Fabales', 'Magnoliopsida', 'Streptophyta'),
    'Quillajaceae': ('Fabales', 'Magnoliopsida', 'Streptophyta'),
    'Surianaceae': ('Fabales', 'Magnoliopsida', 'Streptophyta'),
    # Order Fagales
    'Betulaceae': ('Fagales', 'Magnoliopsida', 'Streptophyta'),
    'Casuarinaceae': ('Fagales', 'Magnoliopsida', 'Streptophyta'),
    'Fagaceae': ('Fagales', 'Magnoliopsida', 'Streptophyta'),
    'Juglandaceae': ('Fagales', 'Magnoliopsida', 'Streptophyta'),
    'Myricaceae': ('Fagales', 'Magnoliopsida', 'Streptophyta'),
    'Nothofagaceae': ('Fagales', 'Magnoliopsida', 'Streptophyta'),
    'Rhoipteleaceae': ('Fagales', 'Magnoliopsida', 'Streptophyta'),
    'Ticodendraceae': ('Fagales', 'Magnoliopsida', 'Streptophyta'),
    # Order Garryales
    'Eucommiaceae': ('Garryales', 'Magnoliopsida', 'Streptophyta'),
    'Garryaceae': ('Garryales', 'Magnoliopsida', 'Streptophyta'),
    # Order Gentianales
    'Apocynaceae': ('Gentianales', 'Magnoliopsida', 'Streptophyta'),
    'Gelsemiaceae': ('Gentianales', 'Magnoliopsida', 'Streptophyta'),
    'Gentianaceae': ('Gentianales', 'Magnoliopsida', 'Streptophyta'),
    'Loganiaceae': ('Gentianales', 'Magnoliopsida', 'Streptophyta'),
    'Rubiaceae': ('Gentianales', 'Magnoliopsida', 'Streptophyta'),
    # Order Geraniales
    'Francoaceae': ('Geraniales', 'Magnoliopsida', 'Streptophyta'),
    'Geraniaceae': ('Geraniales', 'Magnoliopsida', 'Streptophyta'),
    'Melianthaceae': ('Geraniales', 'Magnoliopsida', 'Streptophyta'),
    'Vivianiaceae': ('Geraniales', 'Magnoliopsida', 'Streptophyta'),
    # Order Gunnerales
    'Gunneraceae': ('Gunnerales', 'Magnoliopsida', 'Streptophyta'),
    'Myrothamnaceae': ('Gunnerales', 'Magnoliopsida', 'Streptophyta'),
    # Order Huerteales
    'Dipentodontaceae': ('Huerteales', 'Magnoliopsida', 'Streptophyta'),
    'Gerrardinaceae': ('Huerteales', 'Magnoliopsida', 'Streptophyta'),
    'Tapisciaceae': ('Huerteales', 'Magnoliopsida', 'Streptophyta'),
    # Order Icacinales
    'Icacinaceae': ('Icacinales', 'Magnoliopsida', 'Streptophyta'),
    'Oncothecaceae': ('Icacinales', 'Magnoliopsida', 'Streptophyta'),
    # Order Lamiales
    'Acanthaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Bignoniaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Byblidaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Calceolariaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Carlemanniaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Gesneriaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Lamiaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Linderniaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Lentibulariaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Martyniaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Mazaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Oleaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Orobanchaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Paulowniaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Pedaliaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Phrymaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Plantaginaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Plocospermataceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Schlegeliaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Scrophulariaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Stilbaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Tetrachondraceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Thomandersiaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    'Verbenaceae': ('Lamiales', 'Magnoliopsida', 'Streptophyta'),
    # Order Laurales
    'Atherospermataceae': ('Laurales', 'Magnoliopsida', 'Streptophyta'),
    'Calycanthaceae': ('Laurales', 'Magnoliopsida', 'Streptophyta'),
    'Gomortegaceae': ('Laurales', 'Magnoliopsida', 'Streptophyta'),
    'Hernandiaceae': ('Laurales', 'Magnoliopsida', 'Streptophyta'),
    'Lauraceae': ('Laurales', 'Magnoliopsida', 'Streptophyta'),
    'Monimiaceae': ('Laurales', 'Magnoliopsida', 'Streptophyta'),
    'Siparunaceae': ('Laurales', 'Magnoliopsida', 'Streptophyta'),
    # Order Liliales
    'Alstroemeriaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Campynemataceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Colchicaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Corsiaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Liliaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Melanthiaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Petermanniaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Philesiaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Rhipogonaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    'Smilacaceae': ('Liliales', 'Liliopsida', 'Streptophyta'),
    # Order Magnoliales
    'Annonaceae': ('Magnoliales', 'Magnoliopsida', 'Streptophyta'),
    'Degeneriaceae': ('Magnoliales', 'Magnoliopsida', 'Streptophyta'),
    'Eupomatiaceae': ('Magnoliales', 'Magnoliopsida', 'Streptophyta'),
    'Himantandraceae': ('Magnoliales', 'Magnoliopsida', 'Streptophyta'),
    'Magnoliaceae': ('Magnoliales', 'Magnoliopsida', 'Streptophyta'),
    'Myristicaceae': ('Magnoliales', 'Magnoliopsida', 'Streptophyta'),
    # Order Malpighiales
    'Achariaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Balanopaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Bonnetiaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Calophyllaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Caryocaraceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Centroplacaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Chrysobalanaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Clusiaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Ctenolophonaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Dichapetalaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Elatinaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Erythroxylaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Euphorbiaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Euphroniaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Goupiaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Humiriaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Hypericaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Irvingiaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Ixonanthaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Lacistemataceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Linaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Lophopyxidaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Malpighiaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Ochnaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Pandaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Passifloraceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Peraceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Phyllanthaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Picrodendraceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Podostemaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Putranjivaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Rafflesiaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Rhizophoraceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Salicaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Trigoniaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    'Violaceae': ('Malpighiales', 'Magnoliopsida', 'Streptophyta'),
    # Order Malvales
    'Bixaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Cistaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Cytinaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Dipterocarpaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Malvaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Muntingiaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Neuradaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Sarcolaenaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Sphaerosepalaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    'Thymelaeaceae': ('Malvales', 'Magnoliopsida', 'Streptophyta'),
    # Order Metteniusales
    'Metteniusaceae': ('Metteniusales', 'Magnoliopsida', 'Streptophyta'),
    # Order Myrtales
    'Alzateaceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    'Combretaceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    'Crypteroniaceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    'Lythraceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    'Melastomataceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    'Myrtaceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    'Onagraceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    'Penaeaceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    'Vochysiaceae': ('Myrtales', 'Magnoliopsida', 'Streptophyta'),
    # Order Nymphaeales
    'Cabombaceae': ('Nymphaeales', 'Magnoliopsida', 'Streptophyta'),
    'Hydatellaceae': ('Nymphaeales', 'Magnoliopsida', 'Streptophyta'),
    'Nymphaeaceae': ('Nymphaeales', 'Magnoliopsida', 'Streptophyta'),
    # Order Oxalidales
    'Brunelliaceae': ('Oxalidales', 'Magnoliopsida', 'Streptophyta'),
    'Cephalotaceae': ('Oxalidales', 'Magnoliopsida', 'Streptophyta'),
    'Connaraceae': ('Oxalidales', 'Magnoliopsida', 'Streptophyta'),
    'Cunoniaceae': ('Oxalidales', 'Magnoliopsida', 'Streptophyta'),
    'Elaeocarpaceae': ('Oxalidales', 'Magnoliopsida', 'Streptophyta'),
    'Huaceae': ('Oxalidales', 'Magnoliopsida', 'Streptophyta'),
    'Oxalidaceae': ('Oxalidales', 'Magnoliopsida', 'Streptophyta'),
    # Order Pandanales
    'Cyclanthaceae': ('Pandanales', 'Liliopsida', 'Streptophyta'),
    'Pandanaceae': ('Pandanales', 'Liliopsida', 'Streptophyta'),
    'Stemonaceae': ('Pandanales', 'Liliopsida', 'Streptophyta'),
    'Triuridaceae': ('Pandanales', 'Liliopsida', 'Streptophyta'),
    'Velloziaceae': ('Pandanales', 'Liliopsida', 'Streptophyta'),
    # Order Paracryphiales
    'Paracryphiaceae': ('Paracryphiales', 'Magnoliopsida', 'Streptophyta'),
    # Order Petrosaviales
    'Petrosaviaceae': ('Petrosaviales', 'Liliopsida', 'Streptophyta'),
    # Order Picramniales
    'Picramniaceae': ('Picramniales', 'Magnoliopsida', 'Streptophyta'),
    # Order Piperales
    'Aristolochiaceae': ('Piperales', 'Magnoliopsida', 'Streptophyta'),
    'Hydnoraceae': ('Piperales', 'Magnoliopsida', 'Streptophyta'),
    'Lactoridaceae': ('Piperales', 'Magnoliopsida', 'Streptophyta'),
    'Piperaceae': ('Piperales', 'Magnoliopsida', 'Streptophyta'),
    'Saururaceae': ('Piperales', 'Magnoliopsida', 'Streptophyta'),
    # Order Poales
    'Anarthriaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Bromeliaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Centrolepidaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Cyperaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Ecdeiocoleaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Eriocaulaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Flagellariaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Joinvilleaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Juncaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Mayacaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Poaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Gramineae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Rapateaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Restionaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Thurniaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Typhaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    'Xyridaceae': ('Poales', 'Liliopsida', 'Streptophyta'),
    # Order Proteales
    'Nelumbonaceae': ('Proteales', 'Magnoliopsida', 'Streptophyta'),
    'Platanaceae': ('Proteales', 'Magnoliopsida', 'Streptophyta'),
    'Proteaceae': ('Proteales', 'Magnoliopsida', 'Streptophyta'),
    'Sabiaceae': ('Proteales', 'Magnoliopsida', 'Streptophyta'),
    # Order Ranunculales
    'Berberidaceae': ('Ranunculales', 'Magnoliopsida', 'Streptophyta'),
    'Circaeasteraceae': ('Ranunculales', 'Magnoliopsida', 'Streptophyta'),
    'Eupteleaceae': ('Ranunculales', 'Magnoliopsida', 'Streptophyta'),
    'Lardizabalaceae': ('Ranunculales', 'Magnoliopsida', 'Streptophyta'),
    'Menispermaceae': ('Ranunculales', 'Magnoliopsida', 'Streptophyta'),
    'Papaveraceae': ('Ranunculales', 'Magnoliopsida', 'Streptophyta'),
    'Ranunculaceae': ('Ranunculales', 'Magnoliopsida', 'Streptophyta'),
    # Order Rosales
    'Barbeyaceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    'Cannabaceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    'Dirachmaceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    'Elaeagnaceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    'Moraceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    'Rhamnaceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    'Rosaceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    'Ulmaceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    'Urticaceae': ('Rosales', 'Magnoliopsida', 'Streptophyta'),
    # Order Santalales
    'Amphorogynaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Aptandraceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Balanophoraceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Coulaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Erythropalaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Loranthaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Misodendraceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Nanodeaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Octoknemaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Olacaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Opiliaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Santalaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Schoepfiaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Strombosiaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Thesiaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Viscaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    'Ximeniaceae': ('Santalales', 'Magnoliopsida', 'Streptophyta'),
    # Order Sapindales
    'Anacardiaceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    'Biebersteiniaceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    'Burseraceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    'Kirkiaceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    'Meliaceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    'Nitrariaceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    'Rutaceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    'Sapindaceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    'Simaroubaceae': ('Sapindales', 'Magnoliopsida', 'Streptophyta'),
    # Order Saxifragales
    'Altingiaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Aphanopetalaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Cercidiphyllaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Crassulaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Daphniphyllaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Grossulariaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Haloragaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Hamamelidaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Iteaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Paeoniaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Penthoraceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Peridiscaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Pterostemonaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Saxifragaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    'Tetracarpaeaceae': ('Saxifragales', 'Magnoliopsida', 'Streptophyta'),
    # Order Solanales
    'Convolvulaceae': ('Solanales', 'Magnoliopsida', 'Streptophyta'),
    'Hydroleaceae': ('Solanales', 'Magnoliopsida', 'Streptophyta'),
    'Montiniaceae': ('Solanales', 'Magnoliopsida', 'Streptophyta'),
    'Solanaceae': ('Solanales', 'Magnoliopsida', 'Streptophyta'),
    'Sphenocleaceae': ('Solanales', 'Magnoliopsida', 'Streptophyta'),
    # Order Trochodendrales
    'Trochodendraceae': ('Trochodendrales', 'Magnoliopsida', 'Streptophyta'),
    # Order Vahliales
    'Vahliaceae': ('Vahliales', 'Magnoliopsida', 'Streptophyta'),
    # Order Vitales
    'Vitaceae': ('Vitales', 'Magnoliopsida', 'Streptophyta'),
    # Order Zingiberales
    'Cannaceae': ('Zingiberales', 'Liliopsida', 'Streptophyta'),
    'Costaceae': ('Zingiberales', 'Liliopsida', 'Streptophyta'),
    'Heliconiaceae': ('Zingiberales', 'Liliopsida', 'Streptophyta'),
    'Lowiaceae': ('Zingiberales', 'Liliopsida', 'Streptophyta'),
    'Marantaceae': ('Zingiberales', 'Liliopsida', 'Streptophyta'),
    'Musaceae': ('Zingiberales', 'Liliopsida', 'Streptophyta'),
    'Strelitziaceae': ('Zingiberales', 'Liliopsida', 'Streptophyta'),
    'Zingiberaceae': ('Zingiberales', 'Liliopsida', 'Streptophyta'),
    # Order Zygophyllales
    'Krameriaceae': ('Zygophyllales', 'Magnoliopsida', 'Streptophyta'),
    'Zygophyllaceae': ('Zygophyllales', 'Magnoliopsida', 'Streptophyta'),
    # ===== GYMNOSPERMS =====
    'Araucariaceae': ('Pinales', 'Pinopsida', 'Streptophyta'),
    'Cephalotaxaceae': ('Pinales', 'Pinopsida', 'Streptophyta'),
    'Cupressaceae': ('Pinales', 'Pinopsida', 'Streptophyta'),
    'Pinaceae': ('Pinales', 'Pinopsida', 'Streptophyta'),
    'Podocarpaceae': ('Pinales', 'Pinopsida', 'Streptophyta'),
    'Sciadopityaceae': ('Pinales', 'Pinopsida', 'Streptophyta'),
    'Taxaceae': ('Pinales', 'Pinopsida', 'Streptophyta'),
    'Cycadaceae': ('Cycadales', 'Cycadopsida', 'Streptophyta'),
    'Zamiaceae': ('Cycadales', 'Cycadopsida', 'Streptophyta'),
    'Ginkgoaceae': ('Ginkgoales', 'Ginkgoopsida', 'Streptophyta'),
    'Ephedraceae': ('Ephedrales', 'Gnetopsida', 'Streptophyta'),
    'Gnetaceae': ('Gnetales', 'Gnetopsida', 'Streptophyta'),
    'Welwitschiaceae': ('Welwitschiales', 'Gnetopsida', 'Streptophyta'),
    # ===== FERNS (PPG I 2016) =====
    'Aspleniaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Athyriaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Blechnaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Cyatheaceae': ('Cyatheales', 'Polypodiopsida', 'Streptophyta'),
    'Cystopteridaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Davalliaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Dennstaedtiaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Dicksoniaceae': ('Cyatheales', 'Polypodiopsida', 'Streptophyta'),
    'Dryopteridaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Equisetaceae': ('Equisetales', 'Polypodiopsida', 'Streptophyta'),
    'Gleicheniaceae': ('Gleicheniales', 'Polypodiopsida', 'Streptophyta'),
    'Hymenophyllaceae': ('Hymenophyllales', 'Polypodiopsida', 'Streptophyta'),
    'Lomariopsidaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Lygodiaceae': ('Schizaeales', 'Polypodiopsida', 'Streptophyta'),
    'Marattiaceae': ('Marattiales', 'Polypodiopsida', 'Streptophyta'),
    'Marsileaceae': ('Salviniales', 'Polypodiopsida', 'Streptophyta'),
    'Nephrolepidaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Oleandraceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Onocleaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Ophioglossaceae': ('Ophioglossales', 'Polypodiopsida', 'Streptophyta'),
    'Osmundaceae': ('Osmundales', 'Polypodiopsida', 'Streptophyta'),
    'Polypodiaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Psilotaceae': ('Psilotales', 'Polypodiopsida', 'Streptophyta'),
    'Pteridaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Salviniaceae': ('Salviniales', 'Polypodiopsida', 'Streptophyta'),
    'Schizaeaceae': ('Schizaeales', 'Polypodiopsida', 'Streptophyta'),
    'Selaginellaceae': ('Selaginellales', 'Lycopodiopsida', 'Streptophyta'),
    'Lycopodiaceae': ('Lycopodiales', 'Lycopodiopsida', 'Streptophyta'),
    'Isoetaceae': ('Isoetales', 'Lycopodiopsida', 'Streptophyta'),
    'Tectariaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Thelypteridaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    'Woodsiaceae': ('Polypodiales', 'Polypodiopsida', 'Streptophyta'),
    # ===== BRYOPHYTES =====
    'Marchantiaceae': ('Marchantiales', 'Marchantiopsida', 'Marchantiophyta'),
    'Anthocerotaceae': ('Anthocerotales', 'Anthocerotopsida', 'Anthocerotophyta'),
    'Sphagnaceae': ('Sphagnales', 'Sphagnopsida', 'Bryophyta'),
    'Polytrichaceae': ('Polytrichales', 'Polytrichopsida', 'Bryophyta'),
    'Bryaceae': ('Bryales', 'Bryopsida', 'Bryophyta'),
    'Mniaceae': ('Bryales', 'Bryopsida', 'Bryophyta'),
    'Hypnaceae': ('Hypnales', 'Bryopsida', 'Bryophyta'),
    'Brachytheciaceae': ('Hypnales', 'Bryopsida', 'Bryophyta'),
    'Dicranaceae': ('Dicranales', 'Bryopsida', 'Bryophyta'),
    'Funariaceae': ('Funariales', 'Bryopsida', 'Bryophyta'),
    'Pottiaceae': ('Pottiales', 'Bryopsida', 'Bryophyta'),
    'Grimmiaceae': ('Grimmiales', 'Bryopsida', 'Bryophyta'),
    # ===== GREEN ALGAE =====
    'Chlorellaceae': ('Chlorellales', 'Trebouxiophyceae', 'Chlorophyta'),
    'Ulvaceae': ('Ulvales', 'Ulvophyceae', 'Chlorophyta'),
    'Chlamydomonadaceae': ('Chlamydomonadales', 'Chlorophyceae', 'Chlorophyta'),
    'Caulerpaceae': ('Bryopsidales', 'Ulvophyceae', 'Chlorophyta'),
    'Codiaceae': ('Bryopsidales', 'Ulvophyceae', 'Chlorophyta'),
}

print(f'# loaded {len(PLANT_FAMILIES)} family entries')

# Construct VALUES list for an UPDATE FROM. SQL-escape names (no quotes in family names).
values = []
for family, (order, klass, phylum) in PLANT_FAMILIES.items():
    f_safe = family.replace("'", "''")
    o_safe = order.replace("'", "''")
    c_safe = klass.replace("'", "''")
    p_safe = phylum.replace("'", "''")
    values.append(f"('{f_safe}','{o_safe}','{c_safe}','{p_safe}')")

values_sql = ',\n  '.join(values)

update_sql = f"""
BEGIN;

CREATE TEMP TABLE _plant_lineage (family text PRIMARY KEY, taxorder text, taxclass text, phylum text);
INSERT INTO _plant_lineage VALUES
  {values_sql};

UPDATE resolved_taxonomy rt
SET taxorder = pl.taxorder,
    taxclass = pl.taxclass,
    phylum = pl.phylum
FROM _plant_lineage pl
WHERE LOWER(rt.family) = LOWER(pl.family)
  AND (rt.taxorder IS NULL OR rt.taxclass IS NULL OR rt.phylum IS NULL
       OR LOWER(rt.taxclass) <> LOWER(pl.taxclass)
       OR LOWER(rt.phylum)   <> LOWER(pl.phylum));

SELECT 'Backfill complete' AS msg;
SELECT 'Lineage coverage now:' AS msg,
       COUNT(*) FILTER (WHERE family IS NOT NULL) AS with_family,
       COUNT(*) FILTER (WHERE taxorder IS NOT NULL) AS with_order,
       COUNT(*) FILTER (WHERE taxclass IS NOT NULL) AS with_class,
       COUNT(*) FILTER (WHERE phylum IS NOT NULL) AS with_phylum,
       COUNT(*) AS total FROM resolved_taxonomy;

SELECT 'Asteraceae check:' AS msg;
SELECT family, taxorder, taxclass, phylum, COUNT(*) AS n
FROM resolved_taxonomy
WHERE family = 'Asteraceae'
GROUP BY 1,2,3,4;

COMMIT;
"""

import subprocess
r = subprocess.run(['sudo','-u','postgres','psql','-d','theobroma','-c',update_sql],
                   capture_output=True, text=True, check=True)
print(r.stdout)
print('# done')
